---
title: "R Notebook"
output: html_notebook
---



```{r}
library(igraph)
library(network)
library(sna) 
library(visNetwork)
library(threejs)
library(threejs)
library(ndtv)
library(spaa)
library(png)
library(ggraph)
library(networkD3)
library(animation)
library(maps)
library(geosphere)
source("./Functions.R")
```

Vertex to show connectance, not distance
```{r}
dist_curr_gal<-load_order_convert_csv_to_distanceMat(filepath ="../Matrices/Galapagos/Matrices-Currents_Galap/matrix_median_min_final_Galapagos.csv")

dist.Curr <- 1/dist_curr_gal
```


```{r}
links_curr_galap<-dist2list(dist.Curr)

#removing loops
links_curr_galap1<-links_curr_galap[which(links_curr_galap$col != links_curr_galap$row),]

net <- graph_from_data_frame(d=links_curr_galap1, directed=F)

links<-E(net)
vertex<-V(net)

```


```{r}

x_vec <- c()

set_vertex_attr(net, name = x, index = V(net), value)

vertex.attributes(net)

```















-------------------------------


```{r}


E(net)$width <- E(net)$value*300

l <- layout_with_fr(net)
plot(net, layout=l)

library(maps)
library(network)

map("world", regions = "Galapagos Islands",fill=TRUE,col='#f2f2f2',lwd=0.08)



map('world',col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05,mar=rep(0,4),border=0, ylim=c(-80,80) )
points(x=Galapagos_points$long, y=Galapagos_points$lat, col="slateblue", cex=3, pch=20)


Galapagos_points <- read.csv("../Data/Data_Galapagos/Galapagos-points1.csv",
                             header=TRUE, sep=",") 
```





## Qgraphs

```{r}
area=df_area$area
ages=df_Ages$age

curr_matrix1

p <-  qgraph(dist_curr_gal*-1, layout='spring', 
                         vsize=7,
                         theme="Hollywood",
                         maximum=1000,
                         aspect=TRUE)
x <- qgraph(dist.Curr, 
            layout="spring", 
            vsize=7,
            theme="Hollywood",
            minimum=0.0000000000, #to ensure there is no omision of low values
            ) 

centrality(p)
centralityPlot(x, scale = "raw0",include = 
               c("InDegree","Closeness","Betweenness","OuExpectedInfluence"),
               orderBy ="InDegree")
```

```{r}
df_Ages
```




#-------------- Distance matrices as Qgraphs

## Convert any 0 to 0.01 (minimum distance allowed), to avoid infinite values in the 1/dist

```{r}
distFlor[] <- if_else(distFlor<0.01, 0.01, distFlor[])
distFlor.low[] <- if_else(distFlor.low<0.01, 0.01, distFlor.low[])
distFlor.nat[] <- if_else(distFlor.nat<0.01, 0.01, distFlor.nat[])
distFlor.tha[] <- if_else(distFlor.tha<0.01, 0.01, distFlor.tha[])
distFlor.Lit[]  <- if_else(distFlor.Lit<0.01, 0.01, distFlor.Lit[])
distFlor.Litex[] <- if_else(distFlor.Litex<0.01, 0.01, distFlor.Litex[])
distFlor.fleshy[] <- if_else(distFlor.fleshy<0.01, 0.01, distFlor.fleshy[])

dist_Ages[] <- if_else(distAges<0.01, 0.01, distAges[])
```

```{r}
dist_curr_gal1 <- 1/dist_curr_gal

qgraph(dist_curr_gal1, layout='spring', vsize=7)
```



## Qgraphs
```{r}

dist.flor <- 1/distFlor # one over, as qgraph takes similarity matrices as input
dist.flor.low <- 1/distFlor.low
dist.flor.nat <- 1/distFlor.nat
dist.flor.tha <- 1/distFlor.tha

distflor.Lit <- 1/distFlor.Lit
distflor.Litex <- 1/distFlor.Litex
distflor.fleshy <- 1/distFlor.fleshy

dist.flor.Lit <- 1/distFlor.Lit
dist.flor.Litex <- 1/distFlor.Litex
dist.Flor.fleshy <- 1/distFlor.fleshy


dist.Curr <- 1/distCurr
dist.Geo <- 1/distGeo

############# All species
png('Flor-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
x <- qgraph(dist.flor, layout='spring', vsize=7)

dev.off()

############# lowlands
png('Flor.low-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(dist.flor.low, layout='spring', vsize=7)
dev.off()

############# natives
png('Flor.nat-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(dist.flor.nat, layout='spring', vsize=7)
dev.off()

############# tha
png('Flor.tha-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(dist.flor.tha, layout='spring', vsize=7)
dev.off()

############# Litt
png('Flor.Litt-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(distFlor.Lit, layout='spring', vsize=7)
dev.off()

############# Littex
png('Flor.Littex-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(distFlor.Litex, layout='spring', vsize=7)
dev.off()

############# fleshy
png('Flor.fleshy-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph(distFlor.fleshy, layout='spring', vsize=7)
dev.off()

############# currents
png('Curr_meanmin-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph_Curr.dist<-qgraph(dist.Curr, layout='spring', 
                         vsize=8, 
                         edge.width=3,
                         theme="Hollywood")
dev.off()

############# geographical distances
png('Geo-dist-matrix_forcedraw1.png', width=1000, height=1000, unit='px')
qgraph_Geo.dist<-qgraph(dist.Geo, layout='spring', 
                         vsize=8, 
                         edge.width=3,
                         theme="Hollywood")
dev.off()
```


