---
title: "R Notebook"
output: html_notebook
---
```{r}
library(igraph)
library(ggplot2)
library(gridExtra)
```

```{r}
my_theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```


## currents

Read directed matrices

```{r}
mat_median_min_singlepoints_gal <- readRDS(here::here("c_output/current_conn_matrices/mat_median_min_singlepoints_gal.rds"))
mat_median_min_singlepoints_can <- readRDS(here::here("c_output/current_conn_matrices/mat_median_min_singlepoints_can.rds"))
mat_median_min_singlepoints_az <- readRDS(here::here("c_output/current_conn_matrices/mat_median_min_singlepoints_az.rds"))

```


## geo

```{r}
mat_geo_gal <- read.csv(here::here("b_data/Data_Galapagos/geographic_distance_galap.csv"))
rownames(mat_geo_gal) <- mat_geo_gal[,1]
mat_geo_gal<-mat_geo_gal[,-1]

mat_geo_can <- read.csv(here::here("b_data/Data_Canaries/geographic_distance_canaries.csv"))
rownames(mat_geo_can) <- mat_geo_can[,1]
mat_geo_can<-mat_geo_can[,-1]

mat_geo_az <- read.csv(here::here("b_data/Data_Azores/geographic_distance_azores.csv"))
rownames(mat_geo_az) <- mat_geo_az[,1]
mat_geo_az<-mat_geo_az[,-1]
```

Order names and convert to matrices

```{r}
mat_geo_gal <- as.matrix(mat_geo_gal[order(rownames(mat_geo_gal)), order(colnames(mat_geo_gal))])

mat_geo_can <- as.matrix(mat_geo_can[order(rownames(mat_geo_can)), order(colnames(mat_geo_can))])

mat_geo_az <- as.matrix(mat_geo_az[order(rownames(mat_geo_az)), order(colnames(mat_geo_az))])

```


```{r}

# Create graph objects for currents (directed) and geographic distances (undirected)
create_graphs <- function(current_mat, geo_mat) {
  g_currents <- graph_from_adjacency_matrix(current_mat, mode = "directed", weighted = TRUE)
  g_geo <- graph_from_adjacency_matrix(geo_mat, mode = "undirected", weighted = TRUE)
  V(g_currents)$name <- as.character(V(g_currents)$name)
  V(g_geo)$name <- as.character(V(g_geo)$name)
  return(list(g_currents = g_currents, g_geo = g_geo))
}

galapagos_graphs <- create_graphs(mat_median_min_singlepoints_gal, mat_geo_gal)
canaries_graphs <- create_graphs(mat_median_min_singlepoints_can, mat_geo_can)
azores_graphs <- create_graphs(mat_median_min_singlepoints_az, mat_geo_az)

```


```{r}
# Function to compute centrality measures
compute_centralities <- function(g_currents, g_geo) {
  centralities <- data.frame(
    island = V(g_currents)$name,
    in_degree_currents = strength(g_currents, mode = "in", weights = E(g_currents)$weight),
    out_degree_currents = strength(g_currents, mode = "out", weights = E(g_currents)$weight),
    closeness_currents = closeness(g_currents, weights = E(g_currents)$weight),
    betweenness_currents = betweenness(g_currents, weights = E(g_currents)$weight),
    degree_geo = strength(g_geo, mode = "all", weights = E(g_geo)$weight),
    closeness_geo = closeness(g_geo, weights = E(g_geo)$weight),
    betweenness_geo = betweenness(g_geo, weights = E(g_geo)$weight)
  )
  return(centralities)
}

galapagos_centralities <- compute_centralities(galapagos_graphs$g_currents, galapagos_graphs$g_geo)
canaries_centralities <- compute_centralities(canaries_graphs$g_currents, canaries_graphs$g_geo)
azores_centralities <- compute_centralities(azores_graphs$g_currents, azores_graphs$g_geo)

# Add archipelago information
galapagos_centralities$archipelago <- "Galapagos"
canaries_centralities$archipelago <- "Canaries"
azores_centralities$archipelago <- "Azores"

# Combine dataframes
centralities_all <- rbind(galapagos_centralities, canaries_centralities, azores_centralities)

```


```{r}


# multiply by 1000 the closeness values to make labels legible

centralities_all$closeness_currents <- centralities_all$closeness_currents*1000
centralities_all$closeness_geo <- centralities_all$closeness_geo*1000

#archipelago_colors = c("skyblue", "lightgreen", "lightcoral")

create_plot <- function(data, x_col, y_col, xlabel, ylabel, title) {
  ggplot(data, aes_string(x = x_col, y = y_col, fill = "archipelago")) +
    geom_point(size = 4, colour = "white", pch = 21, size = 2) +
    labs(title = title, x = xlabel, y = ylabel) +
   # scale_fill_manual(values = archipelago_colors) +
  #  geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed") +
    theme_classic() +
    my_theme+
    theme(legend.title = element_blank(),
          legend.position = "right")
}



# Plotting each centrality measure
plot_in_degree <- create_plot(centralities_all, 
                              x_col = "degree_geo", y_col = "in_degree_currents", title = "",
                              xlabel = "Degree by geographic distance", ylabel = "In-degree by ocean currents")

plot_out_degree <- create_plot(centralities_all, 
                               x_col = "degree_geo", y_col = "out_degree_currents", title = "",
                               xlabel = "Degree by geographic distance", ylabel = "Out-degree by ocean currents")

plot_closeness <- create_plot(centralities_all, 
                              x_col = "closeness_geo", y_col = "closeness_currents", title = "",
                              xlabel = "Closeness by geographic distance", ylabel = "Closeness by ocean currents")

plot_betweenness <- create_plot(centralities_all, 
                                x_col = "betweenness_geo", y_col = "betweenness_currents", title = "",
                              xlabel = "Betweenness by geographic distance", ylabel = "Betweenness by ocean currents")




# Display plots

ggarrange(plot_in_degree, 
          plot_out_degree, 
          plot_closeness, 
          plot_betweenness, 
          ncol = 2, 
          nrow = 2,
          common.legend = TRUE,
          legend = "right",
          labels = LETTERS[1:4])


ggsave(here::here("c_output/figures/plot_centrality_geo_currents.png"), height = 9, width = 9)



```


