---
title: "R Notebook"
output: html_notebook
---


Area

```{r}
df_percent_degree_all

df_area<-read.csv(here::here("b_data/Data_Galapagos/area_islands_galap.csv"))
df_area1<-column_to_rownames(df_area, 'X')
df_area1$island = rownames(df_area1)
df_area_gal <- df_area1
df_area_gal[which(df_area_gal$island == "San_Cristobal"),"island"] <- "SanCristobal"
df_area_gal[which(df_area_gal$island == "Santa_Cruz"),"island"] <- "SantaCruz"
df_area_gal[which(df_area_gal$island == "Santa_Fe"),"island"] <- "SantaFe"

df_area<-read.csv(here::here("b_data/Data_Canaries/area_islands_canaries.csv"))
df_area1<-column_to_rownames(df_area, 'X')
df_area1$island = rownames(df_area1)
df_area_can <- df_area1
df_area_can[which(df_area_can$island == "El_Hierro"),"island"] <- "ElHierro"
df_area_can[which(df_area_can$island == "La_Palma"),"island"] <- "LaPalma"
df_area_can[which(df_area_can$island == "La_Gomera"),"island"] <- "LaGomera"
df_area_can[which(df_area_can$island == "Gran_Canaria"),"island"] <- "GranCanaria"


df_area<-read.csv(here::here("b_data/Data_Azores/area_islands_azores.csv"))
df_area1<-column_to_rownames(df_area, 'X')
df_area1$island = rownames(df_area1)
df_area_az <- df_area1

df_area_all <- rbind(df_area_gal, df_area_can, df_area_az)


df_percent_degree_all <- merge(df_percent_degree_all, df_area_all, by = "island")


df_percent_degree_all
```

Age

```{r}
df_age_gal<-read.csv(here::here("b_data/Data_Galapagos/ages_islands_galap.csv"), sep = ";")
df_age_gal[which(df_age_gal$island == "San_Cristobal"),"island"] <- "SanCristobal"
df_age_gal[which(df_age_gal$island == "Santa_Cruz"),"island"] <- "SantaCruz"
df_age_gal[which(df_age_gal$island == "Santa_Fe"),"island"] <- "SantaFe"

df_age_can<-read.csv(here::here("b_data/Data_Canaries/ages_islands_canaries.csv"), sep = ";")
df_age_can[which(df_age_can$island == "El_Hierro"),"island"] <- "ElHierro"
df_age_can[which(df_age_can$island == "La_Palma"),"island"] <- "LaPalma"
df_age_can[which(df_age_can$island == "La_Gomera"),"island"] <- "LaGomera"
df_age_can[which(df_age_can$island == "Gran_Canaria"),"island"] <- "GranCanaria"


df_age_az<-read.csv(here::here("b_data/Data_Azores/ages_islands_azores.csv"),sep = ";")

df_age_all <- rbind(df_age_gal, df_age_can, df_age_az)


df_percent_degree_all <- merge(df_percent_degree_all, df_age_all, by = "island")


df_percent_degree_all
```


compute closeness from geo matrix, not current matrix

```{r}


library(betareg)
library(lmtest)
library(car)
library(emmeans)
library(rcompanion)

# Ensure archipelago is a factor
df_percent_degree_all$archipelago <- as.factor(df_percent_degree_all$archipelago)

df_percent_degree_all$percent_litt_01 <- df_percent_degree_all$Percent_Littoral/100

# models

model.beta_gal = betareg(percent_litt_01 ~ in_degree + closeness + area + age, data=df_percent_degree_all[which(df_percent_degree_all$archipelago == "Galapagos"),])

model.beta_can = betareg(percent_litt_01 ~ in_degree + closeness + area + age, data=df_percent_degree_all[which(df_percent_degree_all$archipelago == "Canaries"),])

model.beta_az = betareg(percent_litt_01 ~ in_degree + closeness + area + age, data=df_percent_degree_all[which(df_percent_degree_all$archipelago == "Azores"),])


lrtest(model.beta_gal)

summary(model.beta_gal)
summary(model.beta_can)
summary(model.beta_az)


Anova(model.beta)


plot(fitted(model.beta),
     residuals(model.beta))

plot(model.beta_can)
```



```{r}
library(glmmTMB)



# Fit the mixed-effects beta regression model
model.beta.re <- glmmTMB(percent_litt_01 ~ in_degree + closeness + area + age + (1 | archipelago),
                         family = beta_family(), data = df_percent_degree_all)

# Summarize the model
summary(model.beta.re)

```

